name: Publish Release

on:
  release:
    #types:[edited]
    #types: [published]
    types:
      - released
      - prereleased
    #types: [deleted]

jobs:
  publish_release:
    runs-on: ubuntu-18.04

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: release
      if: github.event_name.types == 'released'
      run: echo Release

    - name: release
      if: github.event_name.types == 'prereleased'
      run: echo Prereleased

    - name: Download Release Asset
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: nivaes/download-release-assets@master

    #- name: Publish packages
    #  run: dotnet nuget push ./**/**.nupkg --source nuget.org --api-key ${{secrets.NIVAES_NUGET_TOKEN}}
